### ISSUE TITLE
ability to convert to/from int and uint

### ISSUE THREAD

**Issue by sijad** [lunemec/as#2]
is it possible to add support for converting to/from `int` and `uint`?

**Comment by lunemec** [comment]
@sijad yes, I think so. Would you like to try to implement it?

**Comment by sijad** [comment]
sure, I'll give it a try

**Comment by lunemec** [comment]
@sijad I think its already there `as.Int` and `as.Uint`. I'm now adding support for generic type T so you can do `as.T[uint](any)`
